# Generated by Django 3.0.3 on 2020-05-22 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='number',
            field=models.IntegerField(default=10),
        ),
    ]
