# Generated by Django 3.0.3 on 2020-05-29 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200529_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='entry',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.Entry'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='drug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Drug'),
        ),
    ]
