# Generated by Django 3.0.3 on 2020-06-04 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200529_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='prods',
            field=models.ManyToManyField(to='main.Lot'),
        ),
    ]
