# Generated by Django 3.0.3 on 2020-06-04 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200604_1111'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtt', models.IntegerField()),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Lot')),
            ],
        ),
        migrations.AlterField(
            model_name='prescription',
            name='prods',
            field=models.ManyToManyField(to='main.PrescriptionItem'),
        ),
    ]
