# Generated by Django 3.0.3 on 2020-06-04 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200604_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='prods',
        ),
        migrations.AddField(
            model_name='prescription',
            name='prods',
            field=models.CharField(default='indéfinie', max_length=1024),
        ),
        migrations.DeleteModel(
            name='PrescriptionItem',
        ),
    ]
