# Generated by Django 3.0.3 on 2020-06-06 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20200604_1137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='exp_date',
            new_name='date',
        ),
    ]
