# Generated by Django 2.0 on 2020-06-11 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20200606_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='shp',
            field=models.CharField(default='2.0', max_length=30),
        ),
    ]
